skip-check: &skip-check
  name: Check for [ci skip]
  command: bash .circleci/exit.sh


version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: *skip-check 
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: *skip-check
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
